apiVersion: v1
kind: Service
metadata:
  name: node-hello-world-service
spec:
  type: NodePort
  selector:
    app: node-hello-world
  ports:
    - port: 3000       # Service port
      targetPort: 3000 # Container port
      nodePort: 30080  # Access via <minikube-ip>:30080
